// Generated by PanelNamesGenerator, don't change
namespace Client.Scripts.Ui
{
    public static class Panels
    {
        public const string MainScreen = "MainScreen";
        public const string StartScreen = "StartScreen";
        public const string PauseScreen = "PauseScreen";
        public const string LoseScreen = "LoseScreen";
    }
}